# Generated by Django 4.2.29 on 2026-03-21 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_id', models.CharField(db_index=True, max_length=256)),
                ('patient_language', models.CharField(choices=[('es', 'Spanish'), ('zh', 'Mandarin Chinese'), ('vi', 'Vietnamese'), ('fr', 'French'), ('pt', 'Portuguese'), ('ar', 'Arabic'), ('hi', 'Hindi')], default='es', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('medical_summary', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('patient_to_provider', 'Patient → Provider'), ('provider_to_patient', 'Provider → Patient')], max_length=32)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('medical_flags', models.JSONField(blank=True, default=dict)),
                ('rag_validated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='interpreter.session')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
